import type { Metadata } from "next";
import style from "./admin.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function adminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div className={style.body}>{children}</div>;
}
